"""
Optional email delivery for generated reports.
Set EMAIL_ENABLED=true and configure SMTP env vars to activate.
"""
import logging
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from src.config import (
    EMAIL_ENABLED, SMTP_HOST, SMTP_PORT,
    SMTP_USER, SMTP_PASSWORD, EMAIL_TO,
    COMPANY_NAME,
)

logger = logging.getLogger(__name__)


def send_report_email(report_path: str) -> bool:
    if not EMAIL_ENABLED:
        logger.info("Email delivery disabled (set EMAIL_ENABLED=true to enable).")
        return False

    if not EMAIL_TO or not EMAIL_TO[0]:
        logger.warning("No recipient email addresses configured (EMAIL_TO).")
        return False

    path = Path(report_path)
    if not path.exists():
        logger.error("Report file not found: %s", report_path)
        return False

    msg               = MIMEMultipart()
    msg["From"]       = SMTP_USER
    msg["To"]         = ", ".join(EMAIL_TO)
    msg["Subject"]    = f"[{COMPANY_NAME}] Weekly Business Report — {path.stem}"

    body = (
        f"Hi Team,\n\n"
        f"Please find attached the automated Weekly Business Intelligence Report.\n\n"
        f"Generated by the Automated Report System.\n\n"
        f"—\nDo not reply to this automated message."
    )
    msg.attach(MIMEText(body, "plain"))

    with open(path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{path.name}"')
    msg.attach(part)

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, EMAIL_TO, msg.as_string())
        logger.info("Report emailed to: %s", EMAIL_TO)
        return True
    except smtplib.SMTPException as exc:
        logger.error("SMTP error: %s", exc)
        return False
